"""
Mapa de indicadores SGI: cómo leer cada hoja del FDM y cómo calcular verde/rojo.

Cada indicador tiene:
  - hoja: nombre exacto de la hoja en el FDM
  - pilar: pilar al que pertenece
  - col_den: columna (índice 0-based) del denominador (base)
  - col_num: columna del numerador (gestiones/convertidos/etc.)
  - col_ratio_suc: columna del ratio de la sucursal (si ya está calculado)
  - col_ratio_banco: columna del promedio banco
  - label_den: nombre amigable del denominador
  - label_num: nombre amigable del numerador
  - umbral_tipo: "banco" (vs promedio) o "fijo" (threshold estático)
  - umbral_fijo: valor numérico si umbral_tipo=="fijo"
  - accionable: si la sucursal puede mover este indicador
  - simulable: si se puede simular "si hago X más"
"""

SUCURSAL_CU = 5155
SUCURSAL_NOMBRE = "Villa Ballester"

PILARES = ["Individuos", "Empresas", "Administrativo", "Recupero", "Desarrollo Cartera"]

INDICADORES = [
    # ─── INDIVIDUOS ───────────────────────────────────────────────────────────
    {
        "id": "scoring",
        "label": "Scoring vs Turnos",
        "pilar": "Individuos",
        "hoja": "Scoring",
        "col_den": 5,       # clientes atendidos
        "col_num": 6,       # clientes scoreados
        "col_ratio_suc": 8,
        "col_ratio_banco": 12,
        "label_den": "Atendidos",
        "label_num": "Scoreados",
        "umbral_tipo": "banco",
        "accionable": True,
        "simulable": False,
        "descripcion": "Scoreados / Atendidos en turno",
    },
    {
        "id": "turno_previo",
        "label": "Gestión Previa Turnos Web",
        "pilar": "Individuos",
        "hoja": "Turno previo",
        "col_den": 5,
        "col_num": 6,
        "col_ratio_suc": 8,
        "col_ratio_banco": 12,
        "label_den": "Turnos web",
        "label_num": "Gestionados",
        "umbral_tipo": "banco",
        "accionable": True,
        "simulable": False,
        "descripcion": "Turnos gestionados antes de la visita / Total turnos web",
    },
    {
        "id": "activacion_digital",
        "label": "Activación Digital",
        "pilar": "Individuos",
        "hoja": "Activación digital",
        "col_den": 5,
        "col_num": 6,
        "col_ratio_suc": 8,
        "col_ratio_banco": 12,
        "label_den": "Potenciales",
        "label_num": "Activados",
        "umbral_tipo": "banco",
        "accionable": True,
        "simulable": True,
        "descripcion": "Clientes que activaron BIP/Token/CDNI en turno / Clientes potenciales",
    },
    {
        "id": "crm_ind",
        "label": "Gestión Reclamos CRM (IND)",
        "pilar": "Individuos",
        "hoja": "CRM (IND)",
        "col_den": 5,
        "col_num": 6,
        "col_ratio_suc": 8,
        "col_ratio_banco": 12,
        "label_den": "Casos a vencer",
        "label_num": "Resueltos",
        "umbral_tipo": "banco",
        "accionable": True,
        "simulable": False,
        "descripcion": "Reclamos CRM resueltos / Casos a vencer",
    },
    {
        "id": "campanas_ind",
        "label": "Campañas Comerciales (IND)",
        "pilar": "Individuos",
        "hoja": "Campañas comerciales (IND)",
        "col_den": 5,
        "col_num": 6,
        "col_ratio_suc": 12,
        "col_ratio_banco": 17,
        "label_den": "Prospectos ingresados",
        "label_num": "Prospectos contactados",
        "umbral_tipo": "banco",
        "accionable": True,
        "simulable": True,
        "descripcion": "Prospectos convertidos / Prospectos ingresados",
    },
    {
        "id": "prospecto_dig_ind",
        "label": "Prospectos Digitales (IND)",
        "pilar": "Individuos",
        "hoja": "Prospecto digital (IND)",
        "col_den": 5,
        "col_num": 6,
        "col_ratio_suc": 10,
        "col_ratio_banco": 12,
        "label_den": "Prospectos ingresados",
        "label_num": "Alcance",
        "umbral_tipo": "banco",
        "accionable": True,
        "simulable": True,
        "descripcion": "Prospectos digitales convertidos / Ingresados (MAD / pre-solicitudes)",
    },
    # ─── EMPRESAS ────────────────────────────────────────────────────────────
    {
        "id": "haberes",
        "label": "Pago de Haberes",
        "pilar": "Empresas",
        "hoja": "Cuentas haberes",
        "col_den": 5,
        "col_num": 6,
        "col_ratio_suc": 8,
        "col_ratio_banco": 12,
        "label_den": "Stock mes anterior",
        "label_num": "Stock mes actual",
        "umbral_tipo": "banco",
        "accionable": True,
        "simulable": False,
        "descripcion": "Crecimiento de stock de ordenantes activos vs evolución del banco",
    },
    {
        "id": "crm_emp",
        "label": "Gestión Reclamos CRM (EMP)",
        "pilar": "Empresas",
        "hoja": "CRM (EMP)",
        "col_den": 5,
        "col_num": 6,
        "col_ratio_suc": 8,
        "col_ratio_banco": 12,
        "label_den": "Casos a vencer",
        "label_num": "Resueltos",
        "umbral_tipo": "banco",
        "accionable": True,
        "simulable": False,
        "descripcion": "Reclamos CRM empresas resueltos / Casos a vencer",
    },
    {
        "id": "campanas_emp",
        "label": "Campañas Comerciales (EMP)",
        "pilar": "Empresas",
        "hoja": "Campañas comerciales (EMP)",
        "col_den": 5,
        "col_num": 6,
        "col_ratio_suc": 12,
        "col_ratio_banco": 17,
        "label_den": "Prospectos ingresados",
        "label_num": "Prospectos contactados",
        "umbral_tipo": "banco",
        "accionable": True,
        "simulable": True,
        "descripcion": "Prospectos EMP convertidos / Prospectos ingresados",
    },
    {
        "id": "prospecto_dig_emp",
        "label": "Prospectos Digitales (EMP)",
        "pilar": "Empresas",
        "hoja": "Prospecto digital (EMP)",
        "col_den": 5,
        "col_num": 6,
        "col_ratio_suc": 10,
        "col_ratio_banco": 12,
        "label_den": "Prospectos ingresados",
        "label_num": "Alcance",
        "umbral_tipo": "banco",
        "accionable": True,
        "simulable": True,
        "descripcion": "Prospectos digitales EMP convertidos / Ingresados",
    },
    # ─── ADMINISTRATIVO ───────────────────────────────────────────────────────
    {
        "id": "pla",
        "label": "PLA Preventor",
        "pilar": "Administrativo",
        "hoja": "PLA",
        "col_den": 5,
        "col_num": 6,
        "col_ratio_suc": 8,
        "col_ratio_banco": None,
        "label_den": "Alertas emitidas",
        "label_num": "Resueltas en término",
        "umbral_tipo": "fijo",
        "umbral_fijo": 1.0,
        "accionable": True,
        "simulable": False,
        "descripcion": "Sin alertas pendientes ni resueltas vencidas = Verde",
    },
    {
        "id": "balance_tarjetas",
        "label": "Balance de Tarjetas",
        "pilar": "Administrativo",
        "hoja": "Balance de tarjetas",
        "col_den": 5,
        "col_num": 6,
        "col_ratio_suc": 8,
        "col_ratio_banco": None,
        "label_den": "Días hábiles -2",
        "label_num": "Balances aprobados",
        "umbral_tipo": "fijo",
        "umbral_fijo": 1.0,
        "accionable": True,
        "simulable": False,
        "descripcion": "Balances aprobados ≥ días hábiles -2 = Verde",
    },
    {
        "id": "gestion_tarjetas",
        "label": "Entrega de Tarjetas (con turno)",
        "pilar": "Administrativo",
        "hoja": "Gestión de tarjetas",
        "col_den": 5,
        "col_num": 6,
        "col_ratio_suc": 8,
        "col_ratio_banco": 12,
        "label_den": "Tarjetas entregables",
        "label_num": "Entregadas en turno",
        "umbral_tipo": "banco",
        "accionable": True,
        "simulable": False,
        "descripcion": "Tarjetas entregadas a clientes con turno / Entregables (ReTar gestiona stock)",
    },
    {
        "id": "remediacion",
        "label": "Remediación de Datos",
        "pilar": "Administrativo",
        "hoja": "Remediación de datos",
        "col_den": 5,
        "col_num": 6,
        "col_ratio_suc": 8,
        "col_ratio_banco": 12,
        "label_den": "Alertas emitidas",
        "label_num": "Datos completados",
        "umbral_tipo": "banco",
        "accionable": True,
        "simulable": True,
        "descripcion": "Clientes con datos completos / Clientes con alerta de datos en turno",
    },
    {
        "id": "rotacion_saldos",
        "label": "Rotación de Saldos (Tesorería)",
        "pilar": "Administrativo",
        "hoja": "Rotación saldos",
        "col_den": 5,
        "col_num": 6,
        "col_ratio_suc": 10,
        "col_ratio_banco": None,
        "label_den": "Rotación esperada",
        "label_num": "Rotación real",
        "umbral_tipo": "fijo",
        "umbral_fijo": 0.75,
        "accionable": True,
        "simulable": False,
        "descripcion": "Desvío de rotación ≤ 25% y desvío de asistencia ≤ 25%",
    },
    {
        "id": "nps",
        "label": "NPS",
        "pilar": "Administrativo",
        "hoja": "NPS",
        "col_den": 5,
        "col_num": 6,
        "col_ratio_suc": 8,
        "col_ratio_banco": 12,
        "label_den": "Encuestados",
        "label_num": "Promotores netos",
        "umbral_tipo": "banco",
        "accionable": False,
        "simulable": False,
        "descripcion": "% Promotores - % Detractores vs promedio banco",
    },
    {
        "id": "atms",
        "label": "Gestión ATMs",
        "pilar": "Administrativo",
        "hoja": "ATM's",
        "col_den": None,
        "col_num": None,
        "col_ratio_suc": None,
        "col_ratio_banco": None,
        "label_den": None,
        "label_num": None,
        "umbral_tipo": "banco",
        "accionable": True,
        "simulable": False,
        "descripcion": "UG, UM, Remanente y Desvío de Recomendación vs promedios banco",
        "fuente_externa": "atm",  # se lee del archivo ATMs, no del FDM
    },
    # ─── RECUPERO ────────────────────────────────────────────────────────────
    {
        "id": "campanas_recupero",
        "label": "Campañas de Recupero + Seguros",
        "pilar": "Recupero",
        "hoja": "Campañas de recupero",
        "col_den": 5,
        "col_num": 6,
        "col_ratio_suc": 8,
        "col_ratio_banco": 12,
        "label_den": "Casos activos",
        "label_num": "Gestionados",
        "umbral_tipo": "banco",
        "accionable": True,
        "simulable": False,
        "descripcion": "Docs judiciales, cajas de seguridad, fallecidos, siniestros — permanencia < 60 días",
    },
    {
        "id": "mora_temprana",
        "label": "Recupero Mora Temprana",
        "pilar": "Recupero",
        "hoja": "Recupero de dinero",
        "col_den": 5,
        "col_num": 6,
        "col_ratio_suc": 8,
        "col_ratio_banco": 12,
        "label_den": "Cartera total",
        "label_num": "Deuda en mora temprana",
        "umbral_tipo": "banco",
        "accionable": True,
        "simulable": False,
        "descripcion": "Deuda en mora temprana (< 90 días) / Cartera total — menor es mejor",
        "invertido": True,  # menor ratio = mejor
    },
]

# Índice rápido por id
INDICADORES_IDX = {ind["id"]: ind for ind in INDICADORES}

# Colores BP
COLOR_VERDE = "#00A651"
COLOR_ROJO = "#e53e3e"
COLOR_GRIS = "#999999"
COLOR_AMARILLO = "#f6ad55"
